server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
  #ignored-services: microservicecloud-dept
  prefix: /atguigu #公共前缀
  ignored-services: "*"
  routes:
    dept:
      path: /myusers/**
      serviceId: microservicecloud-dept

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}$
  build.version: ${project.version}$

